insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('NT-4UOGE', 'Dodge', 'Ram 2500 Club', 4605, 4, 249);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('ON-SVS9R', 'Porsche', '911', 1811, 4, 200);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('KS-AXXIW', 'Toyota', 'Tundra', 8342, 4, 177);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('QD-BR9HP', 'Honda', 'S2000', 8255, 4, 203);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('PA-YN0D6', 'Hyundai', 'Genesis', 6379, 3, 284);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('UC-KJDIM', 'Acura', 'RSX', 7008, 4, 191);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('NE-ZEOPI', 'Ferrari', 'F430', 6868, 3, 473);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('FC-D2W65', 'Jaguar', 'X-Type', 9080, 4, 302);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('HZ-T27PV', 'Honda', 'Prelude', 7732, 5, 160);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('AR-JACJE', 'Ford', 'Taurus', 9438, 3, 421);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('MF-093MP', 'Toyota', 'RAV4', 4800, 4, 164);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('SG-V706I', 'Subaru', 'Impreza', 7496, 3, 298);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('ME-SHVGY', 'Mitsubishi', 'Galant', 2065, 5, 181);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('LC-XFX5N', 'Volkswagen', 'Golf', 7284, 4, 318);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('AA-PPJ2R', 'Chevrolet', 'Monte Carlo', 7468, 4, 148);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('TP-B5WJM', 'Chevrolet', 'Express 1500', 4140, 3, 270);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('YZ-Z6G00', 'Ford', 'F-Series Super Duty', 1714, 4, 257);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('JW-XXB3H', 'Mercury', 'Grand Marquis', 6443, 3, 278);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('JQ-HCEWA', 'Lexus', 'SC', 8204, 3, 149);
insert into cars (licenceNo, brand, model, mileage, passengers, price) values ('CA-C1TM8', 'Dodge', 'Sprinter', 2636, 4, 297);
